# Generated by Django 4.0.3 on 2022-04-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, default='', max_length=50)),
                ('MiddleName', models.CharField(blank=True, default='', max_length=50)),
                ('LastName', models.CharField(blank=True, default='', max_length=50)),
                ('MobileNumber', models.CharField(blank=True, default='', max_length=10)),
                ('Designation', models.CharField(choices=[('Intern', 'Intern'), ('Junior Developer', 'Junior Developer'), ('Senior Developer', 'Senior Developer')], default='Intern', max_length=50)),
                ('Joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('Reason', models.TextField(blank=True, default='', max_length=500)),
                ('Approved', models.BooleanField(default=False)),
            ],
        ),
    ]
