# Generated by Django 4.0.3 on 2022-04-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_leaves_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='Rejected',
            field=models.BooleanField(default=False),
        ),
    ]
