# Generated by Django 4.0.3 on 2022-04-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_leaves_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='Rejected',
            field=models.BooleanField(default=True),
        ),
    ]
