# Generated by Django 4.0.3 on 2022-04-18 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_leaves_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leaves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.leaves')),
            ],
        ),
    ]
