# Generated by Django 4.0.3 on 2022-04-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='Cancel',
            field=models.CharField(choices=[('Delete', 'Delete'), ('Cancel', 'Cancel')], default='Cancel', max_length=50),
        ),
        migrations.DeleteModel(
            name='cancel',
        ),
    ]
