# Generated by Django 4.0.3 on 2022-04-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_leaves_cancel_delete_cancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days', models.DateField(blank=True)),
                ('note', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='Cancel',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Joined',
            field=models.DateTimeField(blank=True),
        ),
    ]
