# Generated by Django 3.2.12 on 2022-04-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_holidays_note_holidays_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Leaves', models.IntegerField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='holidays',
            old_name='Days',
            new_name='days',
        ),
    ]
