# Generated by Django 4.0.3 on 2022-04-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20220421_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='From',
            field=models.DateField(default='2022-10-14'),
        ),
    ]
