# Generated by Django 4.0.3 on 2022-04-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_leaves_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='To',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leaves',
            old_name='From',
            new_name='start_date',
        ),
    ]
