# Generated by Django 4.0.3 on 2022-04-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_rename_to_leaves_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='LeaveDaysCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaves',
            name='start_date',
            field=models.DateField(),
        ),
    ]
