# Generated by Django 4.0.3 on 2022-04-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_leaves_leavedayscount_alter_leaves_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='Rejected',
        ),
        migrations.AlterField(
            model_name='leaves',
            name='Approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
