# Generated by Django 4.0.3 on 2022-04-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_remove_leaves_rejected_alter_leaves_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave_Configuration',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Designation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Joined',
            new_name='joined',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='MiddleName',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='MobileNumber',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='holidays',
            old_name='days',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='leaves',
            old_name='Approved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='leaves',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='leaves',
            old_name='LeaveDaysCount',
            new_name='leave_days_count',
        ),
        migrations.RenameField(
            model_name='leaves',
            old_name='Reason',
            new_name='reason',
        ),
    ]
