# Generated by Django 4.0.3 on 2022-04-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_delete_leave_configuration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Managment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leaves', models.IntegerField()),
                ('leaves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.leaves')),
            ],
        ),
    ]
