# Generated by Django 4.0.3 on 2022-04-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_leave_managment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_managment',
            name='leaves',
        ),
        migrations.AddField(
            model_name='leave_managment',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
            preserve_default=False,
        ),
    ]
