# Generated by Django 4.0.3 on 2022-04-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_rename_leave_managment_leave_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='total_leaves',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='leave_management',
            name='total_leaves',
            field=models.IntegerField(default=12),
        ),
    ]
